# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            TIL
tagline:          'AI & Backend Developer'
description:      '재밌는 내용을 기록합니다'
url:              https://pyg410.github.io
baseurl:          ""

author:
  name:           '박영규'
  url:            https://github.com/pyg410

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/pyg410/pyg410.github.io
